/*
Name		  : Yash Kumar Singh
Roll Number	  : 1310110373
Program Title : MySQL L2
*/


/* Problem 1 */

CREATE TABLE COURSES(
courseID VARCHAR(6) PRIMARY KEY,
courseName VARCHAR(50) NOT NULL,
courseDept VARCHAR(25) NOT NULL,
courseSchool VARCHAR(50) NOT NULL
);

/* Problem 2 */

CREATE TABLE FACULTY(
courseID VARCHAR(6),
facultyName VARCHAR(30) NOT NULL,
facultyPosition VARCHAR(30) NOT NULL,
facultyQualification VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
FOREIGN KEY (courseID) REFERENCES COURSES(courseID)
);

/* Problem 3 */

CREATE TABLE STUDENT(
courseID VARCHAR(6),
studentName VARCHAR(30) NOT NULL,
studentYear INT(1) NOT NULL,
studentMajor VARCHAR(30) NOT NULL,
studentGrade VARCHAR(1) NOT NULL DEFAULT 'I',
FOREIGN KEY (courseID) REFERENCES COURSES(courseID)
);

/* Problem 4 */

INSERT INTO COURSES VALUES('CSD101','INTRODUCTION TO PROGRAMMING','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD201','DATA STRUCTURES','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD202','INTRODUCTION TO DATABASE MANAGEMENT SYSTEMS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD203','PRINCIPLES OF PROGRAMMING LANGUAGES','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD204','OPERATING SYSTEMS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD301','SOFTWARE ENGINEERING','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD302','DESIGN AND ANALYSIS OF ALGORITHMS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD303','THEORY OF COMPUTATION','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD304','COMPUTER NETWORKS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD305','COMPUTER ARCHITECTURE','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD306','COMPILER DESIGN','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD323','WIRELESS AND MOBILE SYSTEMS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD335','OBJECT ORIENTED PROGRAMMING IN JAVA','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD337','WIRELESS SENSOR NETWORKS','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD338','INFORMATION THEORY','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');
INSERT INTO COURSES VALUES('CSD342','DATA WAREHOUSING AND DATA MINING','DEPARTMENT OF COMPUTER SCIENCE','SCHOOL OF ENGINEERING');

INSERT INTO FACULTY(courseID,facultyName,facultyPosition) VALUES('CSD101','POOJA MALIK','ASSISTANT PROFESSOR');
INSERT INTO FACULTY(courseID,facultyName,facultyPosition) VALUES('CSD201','POOJA MALIK','ASSISTANT PROFESSOR');
INSERT INTO FACULTY VALUES('CSD202','SNIGDHA BISWAS','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD203','DOLLY SHARMA','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD204','SHASHI PRABH','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD301','SNIGDHA BISWAS','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD302','DEBOPAM ACHARYA','ASSOCIATE PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD303','RAJEEV SINGH','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD304','NIRMALA SHENOY','VISITING FACULTY','PHD');
INSERT INTO FACULTY VALUES('CSD305','RAJEEV SINGH','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD306','SULABH BANSAL','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD323','DEBOPAM ACHARYA','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD335','SULABH BANSAL','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD337','DIVYA LOHANI','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD338','SHASHI PRABH','ASSISTANT PROFESSOR','PHD');
INSERT INTO FACULTY VALUES('CSD342','DOLLY SHARMA','ASSISTANT PROFESSOR','PHD');

INSERT INTO STUDENT VALUES('CSD101','SPARSH KANSAL','1','CSE','B');	
INSERT INTO STUDENT VALUES('CSD201','ATISH MAJUMDAR','2','CSE','A');
INSERT INTO STUDENT VALUES('CSD202','ATISH MAJUMDAR','2','CSE','A');
INSERT INTO STUDENT VALUES('CSD204','ATISH MAJUMDAR','2','CSE','A');
INSERT INTO STUDENT VALUES('CSD203','ATISH MAJUMDAR','2','CSE','A');
INSERT INTO STUDENT VALUES('CSD342','YASH KUMAR SINGH','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD301','YASH KUMAR SINGH','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD302','YASH KUMAR SINGH','3','CSE','B');
INSERT INTO STUDENT VALUES('CSD303','YASH KUMAR SINGH','3','CSE','B');
INSERT INTO STUDENT VALUES('CSD304','SHANTNU PATLAN','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD305','SHANTNU PATLAN','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD306','ANUSHREE SHARMA','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD323','ANUSHREE SHARMA','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD335','MANAV SETHI','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD337','HOSHANK AILANI','3','CSE','B');
INSERT INTO STUDENT VALUES('CSD337','KUMAR AMIT SINHA','3','CSE','B');
INSERT INTO STUDENT VALUES('CSD342','ARPAN MANGAL','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD342','MANAV SETHI','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD201','PRERIT TRIPATHI','3','ECE','C');
INSERT INTO STUDENT VALUES('CSD101','AMAN GEETEY','3','ECE','A');
INSERT INTO STUDENT VALUES('CSD101','AMAN SHARMA','3','ECE','A');
INSERT INTO STUDENT VALUES('CSD101','AKHIL SHARMA','3','ECE','A');
INSERT INTO STUDENT VALUES('CSD101','PALASH JAIN','3','ECE','A');
INSERT INTO STUDENT VALUES('CSD304','HARSHIL VORA','3','CSE','A');
INSERT INTO STUDENT VALUES('CSD304','RAMESH MALIK','3','MECH','D');
INSERT INTO STUDENT VALUES('CSD302','DARSHIL SAFARI','3','CIVIL','F');

/* Problem 5 */

/* (a) */

SELECT courseID,courseName FROM COURSES;

/* (b) */

SELECT studentName,courseID FROM STUDENT WHERE studentGrade = 'I';

/* (c) */

SELECT facultyName AS Name, facultyQualification AS Qualification FROM FACULTY,COURSES WHERE COURSES.courseID = FACULTY.courseID AND COURSES.courseName LIKE 'D%';

/* (d) */

SELECT * FROM STUDENT WHERE studentYear = '1'
UNION
SELECT * FROM STUDENT WHERE studentYear = '4';

/* (e) */

SELECT studentName FROM STUDENT WHERE courseID = 'CSD204' IN (SELECT studentName FROM STUDENT WHERE courseID = 'CSD202');

/* (f) */

SELECT * FROM COURSES,STUDENT;

/* (g) */

SELECT studentName, studentYear, studentMajor FROM STUDENT,COURSES WHERE COURSES.courseID = STUDENT.courseID AND COURSES.courseName IN ('DATA STRUCTURES','OPERATING SYSTEMS');

/* (h) */

SELECT * FROM FACULTY WHERE facultyName LIKE 'D%';

/* (i) */

SELECT studentName AS Name FROM STUDENT WHERE studentYear BETWEEN 2 AND 4;


