/*
Name		  : Yash Kumar Singh
Roll Number	  : 1310110373
Program Title : MySQL L6
*/


/* Problem 1 */

/* (a) */

ALTER TABLE FACULTY ADD COLUMN joinYear INT(4);
UPDATE FACULTY SET joinYear = '2011';
UPDATE FACULTY SET joinYear = '2015' WHERE (facultyName = 'POOJA MALIK' OR facultyName = 'DOLLY SHARMA' OR facultyName = 'SULABH BANSAL' OR facultyName = 'NIRMALA SHENOY');
UPDATE FACULTY SET joinYear = '2014' WHERE facultyName = 'SNIGDHA BISWAS';

CREATE TABLE FURTHERINFOFACULTY AS SELECT facultyName,facultyPosition,facultyQualification,joinYear FROM FACULTY;
ALTER TABLE FACULTY DROP COLUMN facultyPosition;
ALTER TABLE FACULTY DROP COLUMN facultyQualification;
ALTER TABLE FACULTY DROP COLUMN joinYear;

/* (b) */

CREATE TABLE FURTHERINFOCOURSES AS SELECT courseID,courseName,courseDept,courseSchool FROM COURSES;
ALTER TABLE COURSES DROP COLUMN courseName;
ALTER TABLE COURSES DROP COLUMN courseDept;
ALTER TABLE COURSES DROP COLUMN courseSchool;

CREATE TABLE FURTHERINFOSTUDENT AS SELECT studentName,studentMajor,studentYear FROM STUDENT;
ALTER TABLE STUDENT DROP COLUMN studentMajor;
ALTER TABLE STUDENT DROP COLUMN studentYear;

/* (c) */

CREATE VIEW CARTESIAN AS SELECT * FROM FURTHERINFOCOURSES,FURTHERINFOSTUDENT,FURTHERINFOFACULTY;

/* (d) */

DELIMITER //
CREATE PROCEDURE creatingView(IN PARAM1 VARCHAR(30))
BEGIN
DECLARE numberOfCourses INT(3);
DECLARE numberOfStudents INT(3);
SELECT COUNT(*) INTO numberOfCourses FROM FACULTY GROUP BY facultyName HAVING facultyName = PARAM1;
SELECT COUNT(*) INTO numberOfStudents FROM FACULTY,STUDENT WHERE STUDENT.courseID = FACULTY.courseID GROUP BY (facultyName) HAVING facultyName = PARAM1;
DROP TABLE IF EXISTS FVIEW;
CREATE TABLE FVIEW AS SELECT DISTINCT facultyName,numberOfCourses,numberOfStudents FROM FACULTY WHERE facultyName = PARAM1;
DROP VIEW IF EXISTS FnameTempView;
CREATE VIEW FnameTempView AS SELECT * FROM FVIEW;
END
//
DELIMITER ;

DROP PROCEDURE creatingView;



